#Basic Container
FROM alpine:latest

#Installing necessary packages
RUN apk add --no-cache bash bash-doc bash-completion
RUN apk add --no-cache musl-dev
RUN apk add --no-cache gfortran

#Assigning default directory
WORKDIR /fortran

